@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeletePlanCommandParser" as DeletePlanCommandParser LOGIC_COLOR
participant "d:DeletePlanCommand" as DeletePlanCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("delete 1")
activate AddressBookParser

create DeletePlanCommandParser
AddressBookParser -> DeletePlanCommandParser
activate DeletePlanCommandParser

DeletePlanCommandParser --> AddressBookParser
deactivate DeletePlanCommandParser

AddressBookParser -> DeletePlanCommandParser : parse("1")
activate DeletePlanCommandParser

create DeletePlanCommand
DeletePlanCommandParser -> DeletePlanCommand
activate DeletePlanCommand

DeletePlanCommand --> DeletePlanCommandParser : d
deactivate DeletePlanCommand

DeletePlanCommandParser --> AddressBookParser : d
deactivate DeletePlanCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeletePlanCommandParser -[hidden]-> AddressBookParser
destroy DeletePlanCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> DeletePlanCommand : execute()
activate DeletePlanCommand

DeletePlanCommand -> Model : deletePlan(1)
activate Model

Model --> DeletePlanCommand
deactivate Model

create CommandResult
DeletePlanCommand -> CommandResult
activate CommandResult

CommandResult --> DeletePlanCommand
deactivate CommandResult

DeletePlanCommand --> LogicManager : result
deactivate DeletePlanCommand

[<--LogicManager
deactivate LogicManager
@enduml
